version: "3.5"
services:
  keycloak:
    image: jboss/keycloak
    command: ["-b", "0.0.0.0", "-Djboss.socket.binding.port-offset=1000"]
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 9080:9080
